### ISSUE TITLE
prepare maven publishing for this artifact

### ISSUE THREAD

**Issue by manolo** [vaadin/example-data#10]
The group should be changed to `com.vaadin`
The main Java package should be `com.vaadin.exampledata`

**Comment by ZheSun88** [comment]
- consider to update the `vaadin.version` to latest before publishing, if it is needed

- also need to add `vaadin-parent` into the root pom for signing the GPG before publishing to maven. 
```
<parent>
        <groupId>com.vaadin</groupId>
        <artifactId>vaadin-parent</artifactId>
        <version>2.0.3</version>
    </parent>
```

one option would be this directory https://repo1.maven.org/maven2/com/vaadin/addon/
but it is okay to be under https://repo1.maven.org/maven2/com/vaadin/ too
