### ISSUE TITLE
Email generator does not pass javax.validation.constraints.Email validation

### ISSUE THREAD

**Issue by manolo** [vaadin/example-data#9]
How to reproduce
- go to start.vaadin.com
- select master detail JavaScript
- Add the following annotation
```
 @Email
  private String email;
```
- Run the project, it will not start because generator saves invalid email

This makes difficult demonstrate TS form validation by using javax.validations

**Comment by Artur-** [comment]
Fixed in 805afb4e162c50b473647c2c565a95228799dfc5
